version: '3'
services:
  app:
    build: ./
    command: ./main
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=root

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5436:5432
